version: 1

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: daily
    default_reviewers:
      - parkerholladay
    default_assignees:
      - parkerholladay
    allowed_updates:
      - match:
          update_type: security
